### ISSUE TITLE
should this just be merged into scala-swing?

### ISSUE THREAD

**Issue by SethTisue** [benhutchison/ScalaSwingContrib#19]
it's not clear to me from the readme why this should remain a separate project?

**Comment by SethTisue** [comment]
I opened a similar ticket at https://github.com/Sciss/SwingPlus/issues/14

**Comment by benhutchison** [comment]
Its a quiet repo. At this late stage in Swings lifecycle I'd be inclined to leave them separate just to make it easier for the downstream systems.

**Comment by benhutchison** [comment]
But happy to merge if you want that... just not sure if it would lead to much more uptake..

**Comment by SethTisue** [comment]
I don't really have a stake in this, I was just curious, after the recent thread on scala-user
