### ISSUE TITLE
Scala 2.13 support - future of this project?

### ISSUE THREAD

**Issue by OndrejSpanel** [benhutchison/ScalaSwingContrib#20]
Will this package be released for 2.13? 

I will be happy do attempt the porting needed on the source code, as long as I know the version will be eventually released to 2.13.

Or should it be instead merged into scala.swing and released to 2.13 as part of it (#19)? If it should, what could one do for this to happen?

**Comment by Sciss** [comment]
which components are you missing in scala-swing? several things have been merged in the meantime, e.g. color chooser and popup menu. Other things like `GroupPanel` I have currently in [SwingPlus](https://github.com/Sciss/SwingPlus/) project; I think it needs a bit of clean-up, before I would merge `GroupPanel` from swing-plus into scala-swing, though.

**Comment by OndrejSpanel** [comment]
What I use from this project is mostly parts of `TreeXXX` objects, my import is:

```
import scalaswingcontrib.{EditableCellsCompanion, RenderableCellsCompanion, CellView, EditableCells, RenderableCells}
```

I use `TreeEditors`, `TreeRenderers`, `Tree` as well, but as I needed to make many modifications to them, I have them in my source code as a source.

**Comment by Sciss** [comment]
I see; well I also have a more recent build of the tree thing [here](https://github.com/Sciss/ScalaSwingTree). I don't know why I never published for 2.13.0 final, perhaps because I didn't use it in my current projects. Anyway, I published the 2.13 artifact now, so should be available [soon](https://search.maven.org/search?q=scala-swing-tree_2.13).

**Comment by OndrejSpanel** [comment]
Thanks. I am however afraid the version at https://github.com/Sciss/ScalaSwingTree does not include the fixes I have submitted to this repository, therefore most likely I will be unable to use it.

**Comment by benhutchison** [comment]
I dont use this project myself anymore but Im happy to republish binaries
for each new Scala version. So yes Id merge a 2.13 PR.

If Sciss wants to take over the components in another project that's
probably better, given he is more active in this space.

**Comment by OndrejSpanel** [comment]
I have create a 2.13 PR #21

**Comment by benhutchison** [comment]
2.13 support in v1.8 published to maven just now
